# Generated by Django 3.2.4 on 2021-09-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_name', models.TextField(blank=True, max_length=500, null=True)),
                ('product_quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('product_mg', models.FloatField(blank=True, default=0, null=True)),
                ('customer_phone', models.IntegerField(blank=True, default=91, null=True)),
                ('customer_address', models.TextField(blank=True, max_length=500, null=True)),
                ('OrderAt', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
