# Generated by Django 3.2.4 on 2021-09-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210907_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_mg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
    ]
